### ISSUE TITLE
Arabic and Hebrew do no work properly

### ISSUE THREAD

**Issue by fk798** [s0ftik3/reverso-api#11]
Hi!
I was messing around with this package when I found out that the package throws this error upon using getContext with Arabic and Hebrew. e.g.

```
reverso.getContext('meet me half way', 'English', 'Arabic', (response) => {
    console.log(response);
}).catch((err) => {
    console.error(err);
});
```

gives us the error 
```
{
  method: 'getContext',
  error: TypeError: Cannot read property 'trimStart' of undefined
      at C:\Users\faisa\OneDrive\Desktop\TranslateServer\node_modules\reverso-api\src\reverso.js:57:43
      at processTicksAndRejections (internal/process/task_queues.js:95:5)       
}
```

My guess is that it has something to do with those two languages being written right to left while the other languages are written left to right.

**Comment by s0ftik3** [comment]
Good catch, thanks! Fixed in v2.19.2, so be sure to update your package version.
