### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '1')

### ISSUE THREAD

**Issue by Melchyore** [s0ftik3/reverso-api#22]
Hello, when I try to translate the following string `The assignee has a duty toward the assigner and must compensate by: paying an amount equal to 5.00 Euro` to `turkish`, I get the following error:

```
C:\Projects\odrl-translator\server\node_modules\.pnpm\reverso-api@2.22.1\node_modules\reverso-api\src\reverso.js:436
            ][0][1],
                ^
[1]
[1] TypeError: Cannot read properties of undefined (reading '1')
at C:\Projects\odrl-translator\server\node_modules\.pnpm\reverso-api@2.22.1\node_modules\reverso-api\src\reverso.js:436:21
at Array.map (<anonymous>)
at Reverso.getTranslation (C:\Projects\odrl-translator\server\node_modules\.pnpm\reverso-api@2.22.1\node_modules\reverso-api\src\reverso.js:429:52)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Any help, please?

**Comment by s0ftik3** [comment]
update your package version to 2.22.2, fixed the issue.
Be aware, I changed some keys API returns, specifically renamed phrase_source & phrase_target to source_phrases & target_phrases and now those are arrays. See updated README for detailed information about it.

**Comment by Melchyore** [comment]
> update your package version to 2.22.2, fixed the issue. Be aware, I changed some keys API returns, specifically renamed phrase_source & phrase_target to source_phrases & target_phrases and now those are arrays. See updated README for detailed information about it.

Thank you!
