### ISSUE TITLE
new html structure for synonym

### ISSUE THREAD

**Issue by chaoyuim** [s0ftik3/reverso-api#27]
https://github.com/s0ftik3/reverso-api/blob/2eded59c8acc6b5215f7d13ebd8e3703d693c11a/src/reverso.js#L131

the code now does not show full context translations(at least for Dutch) . here is what i have done to list all potential translations . 

```
       // const targetTranslations = $('.translation .display-term')
       //     .text()
       //     .trim()
       //     .split('\n')
     var targetTranslations = [];
    $('.translation .display-term').each(function () { 
        targetTranslations.push($(this).text().trim())
    });
```

Also i am not sure why Dutch Synonym is not available, I added it manually, it is working fine. Could you please add it ? thanks

**Comment by s0ftik3** [comment]
please give a specific example, steps to reproduce with current version of the package. Because I've just tried and it works fine without your workaround.

<img width="612" alt="image" src="https://github.com/s0ftik3/reverso-api/assets/64411317/b8f54cd3-920a-4184-930a-d73464dcf416">

**Comment by s0ftik3** [comment]
additionally to my previous response:
<img width="802" alt="image" src="https://github.com/s0ftik3/reverso-api/assets/64411317/a2685666-4210-4762-bdad-daf4c9280df8">
