### ISSUE TITLE
include audio urls and transliteration?

### ISSUE THREAD

**Issue by robsilva** [s0ftik3/reverso-api#31]
@s0ftik3 Would it possible to add the english transliterations and audio url for translations?e.g.
אֲנִי מַנִּיחַ שֶׁיֵּשׁ דְּבָרִים שֶׁאֲפִלּוּ אֲבוֹת אֵינָם יְכוֹלִים לְתַקֵּן.
"ani maniakh sheyesh devarim sheafilu avott eynam yekholim letaqenn." (transliteration)
Thanks!

**Comment by s0ftik3** [comment]
the main question is, does Reverso actually provide such information? Because if it does, yes, I can implement it in this wrapper.

**Comment by robsilva** [comment]
@s0ftik3 did you see that data anywhere in their response?
