### ISSUE TITLE
Axios need to be updated

### ISSUE THREAD

**Issue by dadodasyra** [s0ftik3/reverso-api#34]
# npm audit report

axios  0.8.1 - 0.27.2
Severity: moderate
Axios Cross-Site Request Forgery Vulnerability - https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
No fix available
node_modules/axios
  reverso-api  *
  Depends on vulnerable versions of axios
  node_modules/reverso-api

**Comment by s0ftik3** [comment]
axios is no longer in use
