### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by AlexandreArduino** [s0ftik3/reverso-api#5]
Hi, I tried to use your package but I've got an error : 403, I founded that the server doesn't want me to access to it. How can I resolve that ?

**Comment by s0ftik3** [comment]
Fixed in 2.16.2 patch. You can re-install the package and everything will work for you.

**Comment by s0ftik3** [comment]
Reverso thought they could ban us, but not today. 😈 
![403](https://http.cat/403)

**Comment by AlexandreArduino** [comment]
Thanks a lot that's work !
