### ISSUE TITLE
Safari compatibility

### ISSUE THREAD

**Issue by mathias4833** [s0ftik3/reverso-api#7]
Using the library to translate words in a frontend, an error occured when loading the lib Reverso-api on `Safari`.

The issue is  due to the use of the regex `Lookbehind` not compatible with Safari:

https://github.com/s0ftik3/reverso-api/blob/2a9cf608ee55c21270ef781a53ae19bb82341340/src/reverso.js#L259#L260

```
phrase_from: sourceExamples[i].match(/(?<=<em>)(.*?)(?=<\/em>)/gi)[0],
phrase_to: targetExamples[i].match(/(?<=<em>)(.*?)(?=<\/em>)/gi)[0],
```

**Comment by mathias4833** [comment]
I prepared a branch with a fix in order to create a pull request with my proposal. But I would need the write rights to be able to push my branch. Thanks

**Comment by s0ftik3** [comment]
Fixed.
