### ISSUE TITLE
403 code

### ISSUE THREAD

**Issue by LinuxTux193** [s0ftik3/reverso-api#9]
hi, I'm using your module but when I use the get translation method it gives me this error:
Error: reverso.net did not respond or there is no translation for the given text.
Error: Request failed with status code 403
  at C:\ Users\User\ Desktop\ programming\JavaScript \GroupHelp\ node_modules\reverso-api\src \ reverso.js: 279: 23
  at processTicksAndRejections (internal /process /task_queues.js: 93: 5)

**Comment by s0ftik3** [comment]
Yes, I see the problem and I'll do my best to fix. It appears, Reverso blacklisted me.

**Comment by s0ftik3** [comment]
Please, re-install the library via **npm i reverso-api** and try again. Let me know if something changed.

**Comment by LinuxTux193** [comment]
No, unfortunately nothing changes

**Comment by s0ftik3** [comment]
What about now? I tried to make the same request via Postman and it worked. I made some fixes and it supposed to work properly. If it doesn't — they've banned your IP address as well as mine. If it's like so, the only one way to bypass it is either to use VPN or reboot your router :)
